
import "./globals.css";
import { Poppins } from "next/font/google";


import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";


const poppins = Poppins({
  subsets: ["latin"],
  weight: "400"
})

export const metadata = {
  title: "Create Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.className}antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <AppSidebar />
            <main className="w-full">
              <SidebarTrigger />
              <Navbar />
              {children}
            </main>
          </SidebarProvider>
        </ThemeProvider>

      </body>
    </html>
  );
}
